version: "3"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
    environment:
      CF_API_TOKEN: ""
    volumes:
      - ./data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
